In [1]:
%run ../common.ipynb

In [2]:
import pymysql
import boto3
from urllib.parse import urlparse, parse_qs
def create_connection(host, user, password, db_name=None):
    try:
        conn = pymysql.connect(
            host=host,
            user=user,
            password=password,
            database=db_name if db_name else None,
            ssl={"ssl": False},
            cursorclass=pymysql.cursors.DictCursor,
            client_flag=pymysql.constants.CLIENT.MULTI_STATEMENTS
        )
        return conn
    except Exception as e:
        print(f"Error connecting to database: {e}")
        return None

In [3]:
def create_database(conn, db_name):
    with conn.cursor() as cursor:
        cursor.execute(f"CREATE DATABASE IF NOT EXISTS {db_name}")
    conn.commit()

In [4]:


def create_tables(conn, db_name):
    with conn.cursor() as cursor:
        cursor.execute(f"USE {db_name}")
        
        if db_name == "UserService":
            tables = {
                "Customers": """
            CREATE TABLE IF NOT EXISTS Customers (
                customer_id INT PRIMARY KEY AUTO_INCREMENT,
                first_name VARCHAR(50),
                last_name VARCHAR(50),
                email VARCHAR(100) UNIQUE,
                phone VARCHAR(30),
                address TEXT,
                city VARCHAR(50),
                state VARCHAR(50),
                zip_code VARCHAR(20),
                country VARCHAR(80),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
                """,
                "LoginHistory": """

                    CREATE TABLE LoginHistory (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    customer_id INT NOT NULL,
                    ip_address VARCHAR(15) NOT NULL,
                    login_attempt ENUM('SUCCESS', 'FAILURE') NOT NULL,
                    login_date DATE NOT NULL,
                    is_suspicious TINYINT(1) NOT NULL DEFAULT 0
                );
                """
            }
        
        elif db_name == "OrderService":
            tables = {
                              "Orders": """
                                    CREATE TABLE Orders (
                            order_id INT PRIMARY KEY AUTO_INCREMENT,
                            customer_id INT,
                            order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            status ENUM('Pending', 'Shipped', 'Delivered', 'Cancelled'),
                            total_amount DECIMAL(10,2)
                                )
                            """,
                              "Order_Items": """
                                        CREATE TABLE Order_Items (
                                order_item_id INT PRIMARY KEY AUTO_INCREMENT,
                                order_id INT,
                                product_id INT,
                                quantity INT,
                                unit_price DECIMAL(10,2),
                                total_price DECIMAL(10,2)
                            );
                            """,

                        "Payments": """
                                    CREATE TABLE Payments (
                                        payment_id INT PRIMARY KEY AUTO_INCREMENT,
                                        order_id INT,
                                        payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                        payment_method ENUM('Credit Card', 'PayPal', 'Gift Card', 'Bank Transfer'),
                                        amount DECIMAL(10,2),
                                        status ENUM('Success', 'Failed', 'Pending'),
                                        FOREIGN KEY (order_id) REFERENCES Orders(order_id)
                                    )
                                """,               
                                 "Purchase_History": """
                                CREATE TABLE Purchase_History (
                                    history_id INT PRIMARY KEY AUTO_INCREMENT,
                                    customer_id INT,
                                    order_id INT,
                                    purchase_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                    amount_spent DECIMAL(10,2),
                                    FOREIGN KEY (order_id) REFERENCES Orders(order_id)
                                );
                """,                "Usage_History": """
                                        CREATE TABLE Usage_History (
                                usage_id INT PRIMARY KEY AUTO_INCREMENT,
                                customer_id INT,
                                product_id INT,
                                usage_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                feedback TEXT,
                                return_status ENUM('Returned', 'Not Returned')
                            );
                """,
                "Transactions": """
                                CREATE TABLE Transactions (
                    transaction_id INT PRIMARY KEY AUTO_INCREMENT,
                    customer_id INT,
                    order_id INT,
                    payment_id INT,
                    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    amount DECIMAL(10,2),
                    transaction_type ENUM('Purchase', 'Refund'),
                    status ENUM('Completed', 'Failed', 'Pending'),
                    FOREIGN KEY (payment_id) REFERENCES Payments(payment_id)
                )  
                """
            }
        
        elif db_name == "MarketingService":
            tables = {
                "CampaignClicks": """
                    CREATE TABLE IF NOT EXISTS CampaignClicks (
                        click_id INT AUTO_INCREMENT PRIMARY KEY,
                        campaign_id INT,
                        customer_id INT,
                        click_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                """,
                "Promotions": """
                    CREATE TABLE IF NOT EXISTS Promotions (
                        promotion_id INT AUTO_INCREMENT PRIMARY KEY,
                        campaign_id INT,
                        discount DECIMAL(5,2),
                        start_date DATE,
                        end_date DATE
                    )
                """
            }
        
        elif db_name == "ProductService":
            tables = {
                "ProductDetails": """
                                CREATE TABLE Products (
                        product_id INT PRIMARY KEY AUTO_INCREMENT,
                        name VARCHAR(100),
                        description TEXT,
                        category VARCHAR(50),
                        price DECIMAL(10,2),
                        stock_quantity INT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    );
                """,
                "Inventory": """
                    CREATE TABLE IF NOT EXISTS Inventory (
                        inventory_id INT AUTO_INCREMENT PRIMARY KEY,
                        product_id INT,
                        quantity INT,
                        last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        FOREIGN KEY (product_id) REFERENCES Products(product_id)
                    )
                """
            }
        
        for table_name, query in tables.items():
            cursor.execute(query)
            print(f"Table {table_name} created successfully in {db_name}.")
    
    conn.commit()

In [5]:
def insert_data(conn, table_name, data):
    with conn.cursor() as cursor:
        placeholders = ', '.join(['%s'] * len(data))
        columns = ', '.join(data.keys())
        sql = f"INSERT INTO {table_name} ({columns}) VALUES ({placeholders})"
        cursor.execute(sql, list(data.values()))
    conn.commit()
    print(f"Data inserted into {table_name}.")

In [6]:

parsed_url = urlparse(USER_MYSQL_URL.replace("jdbc:", ""))  # Remove 'jdbc:' prefix
rds_host = parsed_url.hostname
rds_user = MYSQL_PROPERTIES.get('user')
rds_password = MYSQL_PROPERTIES.get('password')

In [7]:
connection = create_connection(rds_host, rds_user, rds_password)
create_database(connection, "UserService")
create_database(connection, "OrderService")
create_database(connection, "MarketingService")
create_database(connection, "ProductService")
user_conn = create_connection(rds_host, rds_user, rds_password, "UserService")
order_conn = create_connection(rds_host, rds_user, rds_password, "OrderService")
marketing_conn = create_connection(rds_host, rds_user, rds_password, "MarketingService")
product_conn = create_connection(rds_host, rds_user, rds_password, "ProductService")
if user_conn:
    create_tables(user_conn, "UserService")
    
if order_conn:
    create_tables(order_conn, "OrderService")

if marketing_conn:
    create_tables(marketing_conn, "MarketingService")
        
if product_conn:
    create_tables(product_conn, "ProductService")
        
connection.close()
if user_conn:
    user_conn.close()
if order_conn:
    order_conn.close()

if marketing_conn:
    marketing_conn.close()

if product_conn:
    product_conn.close()

NameError: name 'rds_host' is not defined